### ISSUE TITLE
Implement on-disk caching of conversions

### ISSUE THREAD

**Issue by blais** [beancount/beangulp#1]
**[Original report](https://bitbucket.org/blais/beancount/issue/113) by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

**Comment by blais** [comment]
Done.

**Comment by chandler150** [comment]
Congrats!

**Comment by hseg** [comment]
Reading through https://beancount.github.io/docs/importing_external_data.html I notice it still links to this ticket, that doc should be updated.
Thanks for the tool, I'm contemplating switching over from hledger - not yet sure which of the two plays better with my bank's reports. Beancount's docs have been much friendlier, though.
