### ISSUE TITLE
in beangulp/examples/importers/csvbank.py column date conflicts with method date()

### ISSUE THREAD

**Issue by boogiewookie** [beancount/beangulp#107]
It creates a Column named date, but it's already inherited a method named date() from csvbase.Importer. So when CSVMeta.__new__()  creates the column dictionary, it sees date as a method and leaves it out. When it comes time to extract there's no column date in the row and it raises an exception.

As a side note, this scheme of using introspection is pretty hard to trace through. Perhaps a more straightforward scheme, like creating a dictionary to map a column name to a function that extracts a value from the raw row tuple might be better. It'd certainly be easier to grok.

**Comment by dnicolodi** [comment]
I cannot reproduce this:
```
$ python importers/csvbank.py test -v tests/csvbank/statement.csv
* /Users/daniele/src/beangulp/examples/tests/csvbank/statement.csv
  /Users/daniele/src/beangulp/examples/tests/csvbank/statement.csv.beancount
  Assets/US/CSVBank/2016-03-18-csvbank.statement.csv
  PASSED
```
The `csvbase.Importer` is there just for convenience, if you don't like it, don't use it. @blais likes to use `petl` to process his CSVs and there is the `beangulp.petl_utils` to help with that.

**Comment by dnicolodi** [comment]
@boogiewookie Can you please provide more details to reproduce your issue? There are testes for this importer base class that demonstrate that they work as intended. It is possible that I don't understand the description of the issue you give, but Python does not work the way you describe. Without being able to reproduce the issue there isn't much that can be done.

**Comment by boogiewookie** [comment]
Apparently not. When I run your test case it works as expected. I can't
tell from my notes just what I was doing differently when I made the bug
report but let's assume it was some confusion or misconfiguration on my
part. Sorry about that! Please just close the bug. In the unlikely event I
see it again, I'll send a more useful report.

**Comment by yacoob** [comment]
I've just bumped into this :)

```python
class Importer(csvbase.Importer):
  date = csvbase.Date('Posted Transactions Date', '%d/%m/%Y')
```

`pyright` pointed out that:  `Expression of type "Date" is incomaptible with declared type "(self: Self@importer, filepath: str) -> Unknown` . The problem, as I understand it is that:
- `csvbase` expects that you'll define a `date` attribute, which it'll later use to extract and parse date from transaction rows
- At the same time `beangulp.Importer` defines `date` [here](https://github.com/beancount/beangulp/blob/ec3752930efdfa7358890e263f1aba16151ae316/beangulp/importer.py#L72) as part of the Importer protocol. It's a function that should return a date for the entire file for archival purposes.

Curiously enough, [the documentation](https://docs.google.com/document/d/1hBfsHZcoHgz5rvhCdP42g2FJ5ouycIMV4H1tfgXpwBU/edit#heading=h.z153vh2ll6ix) talks about `file_date` . `ImporterProtocol` also mentions `date()` as source of the archival data.

Looks like a genuine conflict of names - I'm unsure what's the proper solution here though - changing the Importer interface to go back to `file_date()` or `csvbase.Importer` extract to use a different field. But for completeness, it feels like `csvbase.TestImporter.test_extract` should test `i

**Comment by dnicolodi** [comment]
pyright apparently does not understand metaclasses. There is no bug or name conflict here. If you don't like the "magic" implemented by the metaclass, you can avoid using it and define the columns with a `columns` class or instance dictionary. See what the metaclass does https://github.com/beancount/beangulp/blob/ec3752930efdfa7358890e263f1aba16151ae316/beangulp/importers/csvbase.py#L156-L168

**Comment by yacoob** [comment]
Glad to hear there's no bug here :) Thanks!
