### ISSUE TITLE
Make duplicate detection configureable

### ISSUE THREAD

**Issue by blais** [beancount/beangulp#2]
**[Original report](https://bitbucket.org/blais/beancount/issue/185) by Jakob Schnitzer (Bitbucket: [yagebu](https://bitbucket.org/yagebu), GitHub: [yagebu](https://github.com/yagebu)).**

----------------------------------------

I'm using Beancount's import mechanism to import the transaction of my main accounts (that are provided as CSV files by my bank). This works quite well in general and is really a step up from doing it all by hand.

Most times duplicates aren't a problem but sometimes I already typed out some transactions by hand that I'm about to import. Since my importer doesn't automatically assign account (which I do by hand on Fava's import page), these don't get recognized as duplicates as the check for duplicates seems to be quite strict.

In my case, the "perfect" duplicate check would only check the amount posted to the checking account that I'm importing the transactions for. So it would be nice if the duplicate check could be configured (and if a "check only amount posted to a single account" would be shipped with Beancount).

I could implement this, if you agree that it would be a useful addition. I would probably add a `duplicate_check(entry1, entry2)` to `importer.ImporterProtocol`.

**Comment by dnicolodi** [comment]
I think that the current transaction comparison function used in deduplication covers this use case already, but it is diffiocult to tell without a concrete example. However, with the new `Importer` interface, the importers can define a `cmp` static method that is used to compare transactions for deduplication or can define a `deduplicate()` method to completely redefine the deduplication behavior.
