### ISSUE TITLE
Colors should be disabled when not supported

### ISSUE THREAD

**Issue by blais** [beancount/beangulp#36]
Running testing from withini Emacs produces escape characters which renders the output garbled.

**Comment by dnicolodi** [comment]
What do you mean with "within Emacs"? Escapes sequences should not be emitted if stdout is not a terminal. For example
```
python examples/office/importers/acme/acme_pdf.py test | cat -
```
does not have escape sequences.

**Comment by blais** [comment]
Just tested. It works in the console.
Somehow doesn't work in Emacs compilation mode.
I get output like this: ... 2015-03-06.AccountStatement.csv^[[0m^[[32m  PASSED^[[0m
(Which means escape sequences are generated.)

**Comment by dnicolodi** [comment]
Click is not smart enough to recognize that the Emacs pty does not support escape sequences. Looking at the Click code, it looks like it emits escape sequences for all output streams for which `isatty()` returns true. I can add a switch to turn off colors or I can add some code that looks at `$TERM` or you can use the `cat -` workaround. What do you think?
