### ISSUE TITLE
What was naming issue with beangulp.importers.csv?

### ISSUE THREAD

**Issue by dnicolodi** [beancount/beangulp#43]
I don't find what was the issue that prompted the rename of `beangulp.importers.csv` to `beangulp.importers.csv_importer`. The latter is a mouthful and a tautology. I think it was something related to Bazel, but I don't find the details. I would like to rename the importer back the original name before releasing beangulp, unless there are compelling reasons.

**Comment by blais** [comment]
Don't rename it, the issue was that importing it would collide with the default module name.
I don't remember all the details, but I do remember spending enough time on it to convince myself it was pathological and unfixable and a lot easier to just rename the module.

**Comment by dnicolodi** [comment]
I was asking because I already renamed it and nothing broke. I also added one more example/test and I haven't found any issue https://github.com/dnicolodi/beangulp/tree/csv-rename

**Comment by blais** [comment]
I can't remember.
Some modules may want to import both, so that's another argument for
distinguishing them.
Rename to csvimp.py if you like that best, but returning to csv.py is 99.9%
certain to cause more problems in the future.

**Comment by dnicolodi** [comment]
I don't see how wanting to import both the `csv` and the `beangulp.importers.csv` modules can be a problem: there are many solutions to avoid the name collisions, such as the `import ... as ...` construct as already used in a couple of places in the codebase. I don't think that anyone with some Python understanding would try to do 
```
from beangulp.importers import csv
import csv
```
and expect it to work in some magical way.

I also don't think that the name collision with a builtin module can be a fundamental problem: beancount has a `beancount.parser.parser` that collides with the builtin `parser` module.

I know, I am obstinate.

**Comment by blais** [comment]
On Sat, Feb 20, 2021 at 9:24 AM Daniele Nicolodi <notifications@github.com>
wrote:

> I don't see how wanting to import both the csv and the
> beangulp.importers.csv modules can be a problem: there are many solutions
> to avoid the name collisions, such as the import ... as ... construct as
> already used in a couple of places in the codebase. I don't think that
> anyone with some Python understanding would try to do
>
I know and understand all this very well  - I wrote snakefood! - but I can
assure you it was causing problems.
I don't remember the detail, but I clearly remember wasting a whole of time
with this a few times and was stubborn about it as well and eventually had
enough.
Look bring it back if you really care, but if I waste one more cycle on
this stupid problem we rename the file
Life's too short
