### ISSUE TITLE
Move the OFX importer to the examples folder?

### ISSUE THREAD

**Issue by dnicolodi** [beancount/beangulp#44]
It has been suggested before but I don't know how many depend on it being importable from `beancount.ingest` or `beangulp` now. Moving it to the examples would still make the code available and we could keep maintaining and testing the basic functionalities, while making it clear that it is not supposed to be a general and complete solution and that users are expected to copy the code in their importers.

**Comment by blais** [comment]
I like it. Let's move it, totally makes sense.

**Comment by dnicolodi** [comment]
Should we maybe postpone all changes that break backward compatibility beyond the import location rename to after the first release of beangulp? I think that an easy migration path from `beancount.ingest` to `beangulp` could be important. If we stick to the new command line interface and the new testing framework for beangulp 0.1 users can quickly migrate to `beangulp` with something like:
1. `pip install beangulp==0.1`
2. edit importers adding:
   ```
   from beancount.testinng import main
   if __name__ == '__main__':
      main(Importer())
   ```
   at the bottom of their importers
3. run `python importer.py generate ...`
4. fix imports till the above command runs successfully
5. verify with `python importer.py test`
6. `pip install beangulp==0.2` introducing backward incompatible changes
7. run `python importer.py test ...` and fix all errors

Having release 0.1 (or what we will decide to call it) introduce backward incompatible changes may make the porting harder. The first release of beangulp can be cut very soon. What other changes other than the new command line interface and the testing would be nice to have?

**Comment by dnicolodi** [comment]
It would be nice to have some input from other users on this.

**Comment by blais** [comment]
Whichever way you want this. My take on it is that this is the next version and breakage is expected, until we stabilize.
I mean, it's pretty close already.
