### ISSUE TITLE
Semantics of guess_file_type()

### ISSUE THREAD

**Issue by dnicolodi** [beancount/beangulp#46]
Currenltly, `guess_file_type()` has some strange properties:

- it may raise an exception if `python-magic` is not installed (I think the idea was to raise an exception instructing the user to install the package, but a missing `raise` makes the code fail with a generic exception),
- it does some manual filename extension matching, instead than injection new mime types mappings into the `mimetypes` module,
- it determined the file type from the file extension through the `mimetypes` module, except when ti doesn't and uses the file content via the `magic` module, without the user having a way to determine which method will be used to provide an answer.

In the effort toward simplification, I would like to revisit this interface.

The easiest thing, would be to make `python-magic` a required dependency and always use the content based detection. However, it is a trivial dependency only on most Linux distributions where `libmagic` is part of a basic installation. On Windows there isn't really an easy way to install the `libmagic` dependency and on macOS it requires installing it via some mean other than `pip`.

The next best thing could be to do not fall back to content based detection. But in this case the function becomes a trivial wrapper around `mimetypes`. I therefore suggest to add a `beangulp.mimetypes` module that does something like
```python
import mimetypes
mimetypes.add_type(...)
```
and deprecate the `beangulp.file_type` module in favor of the standard library `mimetypes` module. I think that content based mimetype detection should be an explicint opt-in, and the magic interface is easy to use.

Alternatively, `guess_file_type()` should always use content based detection, unless it is not available, and fall back to filename extension based detection in this case.

**Comment by blais** [comment]
Sgtm!
This grew over time with  particular needs I had when new files appeared.
Had lots of incremental fixes done over time, sometimes by other users
Let's try the mimetypes approach in a branch and we'll give it a test run
with the union of our files and let's see if we can resolve all.
Thank you Daniele!
