### ISSUE TITLE
Is the support for multiple importers matching the same document useful?

### ISSUE THREAD

**Issue by dnicolodi** [beancount/beangulp#52]
Currently more than one importers can positively identify the same document: all of them are run in sequence to extract entries, the first importer to match and that return a non-None account for the document is used to file the document.

Is this really desired?

I think this was coded this way to have different importers perform different operations on the same files (ie one importer does the extraction and another provides information for document filing). However, I think it takes a quite contrived example to find a case where this saves a significant amount of complexity in the importers. It is also confusing and error prone for the users: an error when more than one importer identifies the same document would be much better.

**Comment by blais** [comment]
You are correct, that's the reason it was devised that way. e.g., some CSV files contain multiple sections and you may want to have separate importers for each section. In practice, it is almost never the same that you really, really need that, so I'm happy to simplify and bring this back to a 1:1 mapping.

You have my blessing!

**Comment by dnicolodi** [comment]
Implemented in #58.

**Comment by umangv** [comment]
Just wanted to add a data point that PNC Bank lumps checking and savings accounts into the same OFX file. There seems to be no way to download separate OFX files.

I have made a change locally to allow doing this via a command-line flag (`--allow-multiaccount-files`) on `extract` and `identify` . Would you be opposed to me bringing this behavior back but guarded by a flag so that it isn't the default behavior? If not, I'll get my change covered by unit tests and send over a PR.

**Comment by umangv** [comment]
Oh, I guess this isn't as big an issue as I thought: an importer is not restricted to generating transactions for a single account. So what I would need to do to make this work is to have a single importer handle multiple accounts in the same bank and then export all transactions from that file.

I guess that's a convoluted way of saying that the change in #58 makes sense to me: it's worth protecting against the possibility that two importers have overly broad match conditions and someone ends up with duplicate (possibly conflicting) transactions as part of an import. The case I was worried about (an institution that bundles transactions from multiple accounts into a single file) can be handled by writing a more complicated importer.
