### ISSUE TITLE
Make importers easier to debug

### ISSUE THREAD

**Issue by blais** [beancount/beangulp#6]
**[Original report](https://bitbucket.org/blais/beancount/issue/275) by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

When an importer doesn't identify, it can be a little puzzling to some users.
We should provided more debugging info, perhaps list the regexps, find out the right amount of "noise" to provide (currently too little noise).

**Comment by dnicolodi** [comment]
@blais, I guess this refers to the behavior of the identifier mixin. I know it is a long time ago, but do you remember more details about this?

**Comment by blais** [comment]
I don't. The idea was to make it easier to debug importers not picking up some files, but now that we've got the importer runnable on a single basis - by running it itself - I think we don't need this anymore. will close
