### ISSUE TITLE
Use enhanced extract methods in standard importer

### ISSUE THREAD

**Issue by blais** [beancount/beangulp#8]
**[Original report](https://bitbucket.org/blais/beancount/issue/288) by Patrick Ruckstuhl (GitHub: [tarioch](https://github.com/tarioch)).**

----------------------------------------

It would be great to change the standard importers to use the new enhanced method. That way they can be easily used with smart_importer. 
I created PR 71 for this.

**Comment by dnicolodi** [comment]
@tarioch Do you remember what this was about? The issue does not really provide enough context for me to understand and the pull request didn't make it to Github during the migration from Bitbucket.

**Comment by tarioch** [comment]
It was about changing the standard importers (like the csv one) to use the interface which also contains the list of existing entries

**Comment by tarioch** [comment]
Just checked I think that was done, so can close this

**Comment by dnicolodi** [comment]
Thank you for confirming.
