### ISSUE TITLE
Add comments to exported transactions

### ISSUE THREAD

**Issue by captn3m0** [beancount/beangulp#87]
I couldn't find any documentation suggesting that this is possible, hence creating this ticket. Not everything about a transaction can/should be encapsulated in metadata/tags/links - I would want to generate a comment containing some of the details about the transaction.

**Comment by dnicolodi** [comment]
I don't understand what you mean by "automatic" in the issue title.

Beangulp uses the Beancount data model to represent ledger entries and this data model does not include a representation for comments, thus adding comments to transactions is not possible. What you can do is to add the information to metadata entries or to the narration and post-process the textual representation of the ledger to convert the extra information into comments.

However, I am not sure I completely understand the use case. Beangulp is about converting some form of structured data into a Beancount ledger. If the data is structured it is worth thinking about a way to represent it in terms that can be understood by Beancount and thus that can be queried from the ledger with Beancount tools. Comments, so far, do not have this property. If you are converting unstructured data of some sort (an example would be useful), maybe Beangulp is not the right tool. The Beancount input format is very easy to generate "by hand" including comments.

**Comment by blais** [comment]
I think he wants a way to render some text in the output as comments.
We could change the interface (huh... nope) or honor a special field of metadata that gets pulled out for rendering as text (easy, doesn't change the interface, doesn't break anything).

**Comment by dnicolodi** [comment]
I don't have anything against adding a special metadata field that gets translated into a comment, in principle (I think that adding a metadata field with a `;` key already does most of what is required) however, I don't want this does not allow to control where the comment is places, and I am sure the next request will be to be able to place the comment in any place you can imagine, and then some...

**Comment by captn3m0** [comment]
Sorry, not sure why I put automatic (I meant auto-generated) there. A metadata field with `;` key sounds good, but I do understand why it won't be enough for some users.

I ended up running through my 3k-line generated file and (just checked) ended up with 70-ish comments, out of which perhaps 20 could have been auto-generated, which isn't really much. There definitely would have been more comments, but I'm not sure if they would have been any more useful, so I'm not entirely sure about my request now.

**Comment by dnicolodi** [comment]
I am not opposed to add features that enable your use case, but for that I need to understand the use case. Can you share an example of transaction with a comment that you would like to be able to emit from a Beangulp importer? It would also be helpful to see the input data from which the transaction is generated.

**Comment by captn3m0** [comment]
Some examples:

```ini
; Flight booking for $PASSENGER LIST
2019-01-01 * "Flight Booking via Amazon"
  link: "https://www.amazon.in/gp/css/summary/edit.html?orderID=..."
  orderid: "..."
  Liabilities:IN:HDFC:CC  -100 INR
  Expenses:Gift
; Payment made partially via AmazonPay. Fix amount later.
2019-01-01 ! "Some Item"
  link: "https://www.amazon.in/gp/css/summary/edit.html?orderID=..."
  orderid: "..."
  Liabilities:IN:HDFC:CC  -100 INR
  ; Fill this later, export file does not have this data
  ; Liabilities:IN:AmazonPay FIXME
  Expenses:Gift
```

I've figured out that using metadata (and postings have metadata as well, which I learned later) fulfills most of first usecase, including for things like shipping addresses. I still can't figure out a way to account for the second usecase, where I know that the payment was made partially via a wallet in addition to my card, but not the actual split (which is missing in the export). Hence, I want to leave an auto-generated comment for the same. 

I've been using a dummy metadata field (AmazonPay: "Yes") for now.

**Comment by dnicolodi** [comment]
Transactions have a payee and a narration. I would have put the information in the first comment in your example in the narration.

I am not sure I understand the second example. Are you saying that you get a transactions export (from Amazon, I imagine) that contains the amount charged to your credit card and the fact that part of the costs have been credited to your Amazon Pay, but not the amount charged to your Amazon Pay, nor the total costs? It does not make much sense. How can this be a thing? From where do you get the amount charged to your Amazon Pay and how can you associate the Amazon Pay transaction to the transaction recorded in the ledger? In this situation I would simply add the `Liabilities:IN:AmazonPay` posting without an amount. This would cause the transaction to be invalid and Beancount would remember you that it needs to be completed. You can also use a dedicated transaction flag that makes it easier to look up this kind of transactions.

I really don't think comments are the right solution here.

**Comment by captn3m0** [comment]
Sadly, it is a thing 😢. 

Here's the corresponding entry in the export file (Generated from https://www.amazon.com/gp/privacycentral/dsar/preview.html)

| Website   | Order ID            | Order Date           | Currency | Unit Price | Unit Price Tax | Shipping Charge | Total Discounts | Total Owed | Shipment Item Subtotal | Shipment Item Subtotal Tax | ASIN       | Product Condition | Quantity | Payment Instrument Type               | Order Status | Shipment Status | Product Name                                 |
|-----------|---------------------|----------------------|----------|------------|----------------|-----------------|-----------------|------------|------------------------|----------------------------|------------|-------------------|----------|---------------------------------------|--------------|-----------------|----------------------------------------------|
| Amazon.in | 171-5527783-AAAAAA | 2018-11-09 13:30 UTC | INR      | 507.63     | 91.37          | 0               | 0               | 599        | 507.63                 | 91.37                      | B06X19FLTC | New               | 1        | Gift Certificate/Card and Visa - XXXX | Closed       | Shipped         | AmazonBasics Extended Gaming Mouse Pad,Black |

The "Payment Instrument Type" mentions "Gift Certificate", but it really means AmazonPay in this case. Screenshots in the Amazon UI all state that while AmazonPay balanced was used, it doesn't tell what was the split. In some cases, the Printable Order Summary has the split, but it doesn't in this case.

![image](https://user-images.githubusercontent.com/584253/121494153-02a5e200-c9c8-11eb-9812-fda281ebc335.png)

My credit card statement records the correct amount charged to my card (455.71 INR).

>I really don't think comments are the right solution here.

Thanks. I'm leaning towards this as well 👍🏽. Good to close?

**Comment by dnicolodi** [comment]
The way Amazon does the reporting is really weird. What I would do is to generate two partial transactions (like I have shown in the previous comment) one from the Amazon report file and one from your credit card statement and combine them either by hand or with a customized deduplication step. IIRC Amazon puts the order number in the CC transaction note and you could use that as a key to identify transactions that need to be combined.

Closing the issue as it seems that there are better alternatives to encode information in comments. The plan is to extend the Beancount parser to record comments too, this will come with a representation for comments in the parsed three and this will allow to generate comments from the importers without having to hack it into Beangulp.
