### ISSUE TITLE
What is the right way to use cvsbase.Importer along with IdentifyMixin and FilingMixin?

### ISSUE THREAD

**Issue by michelgb** [beancount/beangulp#89]
Stupid question from a python newbie. I am trying to write something like this:

```
class MyImporter(IdentifyMixin, FilingMixin, csvbase.Importer):
  def __init__(account, currency, **kwargs):
     super().init(account = account, currency = currency, **kwargs)
```

I noticed that the `extract()` method is returning `None` which makes me think the inheritance from csvbase isn't really working. Looking into the constructors of each class I found something interesting.

- csvbase.Importer takes positional arguments but no **kwargs.
- both mixins take **kwargs but no positional arguments (*args).

I have tried other combinations unsuccessfully.

**Comment by dnicolodi** [comment]
`csvbase.Importer` implements the new `beangulp.Importer` interface and not the old and deprecated `beangulp.importer.ImporterProtocol` interface implemented by the mixins. In other words, the mixins are deprecated, do not work with the new importers interface, and will be removed once the first stable version of beangulp will be released. They are been kept so far only for backward compatibility.

**Comment by michelgb** [comment]
I suggest to add a deprecation comment.
