### ISSUE TITLE
Deduplication is not stable

### ISSUE THREAD

**Issue by nicdumz** [beancount/beangulp#95]
Imagine a setup with:

```
documents/foo.csv
documents/bar.csv
```

And a static importer such as:

```python
class StaticImporter(Importer):
  """No matter the file, identify it and yield the same transaction."""
  def identify(self, filepath):
    return True
  def account(self, filepath):
    return 'Dummy'
  def extract(self, filepath):
    return [DUP_TRANSACTION]
```

This situation is a simplified version of CSV reports with overlapping dates, something that happen if you're not carefully doing CSV exports at specific time boundaries. (e.g. export Jan-June.csv, then March-Sept.csv).

If you assume the following `out.beancount`:

```
;; -*- mode: beancount -*-

**** documents/foo.csv

DUP_TRANSACTION

**** documents/bar.csv

; DUP_TRANSACTION

```

(where the second transaction has been marked as a duplicate and is commented out), then running `extract -o out.beancount -e out.beancount` has the following output:

```
;; -*- mode: beancount -*-

**** documents/foo.csv

; DUP_TRANSACTION

**** documents/bar.csv

DUP_TRANSACTION

```

What was marked as a duplicate before becomes a non-duplicate, and vice-versa.

Ideally, this behavior should be stable so you can re-import data via idempotent behaviors.

Thanks!

**Comment by dnicolodi** [comment]
Assuming that I understood correctly what you are trying to do, I obtain a different result in my attempt at reproducing it. Executing `extract -o out.beancount -e out.beancount` with the setup you descruibe, I obtain a `out.beancount` with two commented out transactions. This is exactly what I would expect as the importer returns two transactions (one for each file processed) which are identical to the one transaction already present the existing ledger.

Please note that called like that (namely with the existing ledger and the output ledger files being the same file) the `extract` command will happily override the existing ledger with a new ledger with exclusively the entries produced by the latest run. In other words, the output of `extract` is not a combination of the existing ledger and the newly extracted entries, but contains only the newly extracted entries.

**Comment by dnicolodi** [comment]
I cannot reproduce the issue and there hasn't been any feedback for over a year.
