### ISSUE TITLE
Should we have a list of beangulp importers?

### ISSUE THREAD

**Issue by ThomasdenH** [beancount/beangulp#97]
I have created a repository with three beangulp importers. Definitely not useful for everyone but maybe to a few. Should there be a list somewhere so that community efforts can be combined to write them?

**Comment by blais** [comment]
Right now the most comprehensive list is:
https://docs.google.com/document/d/1Z37bQ45wDtjTPaMQ_x-f33p1trH9fNosEAUgbQXwp30/edit#heading=h.rs27hvxo0wyl
I think adding a suggestion for your project on the doc is reasonable.

Searching on github is also possible.
